"use strict";

module.exports = {
  title: "Twig",
  id: "1475d705-473d-499b-8694-1373ee9db542", // Keeping UUID from previous edit
  groupPosition: 4, // Playing nice with existing book-data files instead of renumbering

  // First paragraph of https://parahumans.wordpress.com/about/
  description: `The year is 1921, and a little over a century has passed since a great mind unraveled the underpinnings of life itself.  Every week, it seems, the papers announce great advances, solving the riddle of immortality, successfully reviving the dead, the cloning of living beings, or blending of two animals into one.  For those on the ground, every week brings new mutterings of work taken by ‘stitched’ men of patchwork flesh that do not need to sleep, or more fearful glances as they have to step off the sidewalks to make room for great laboratory-grown beasts.  Often felt but rarely voiced is the notion that events are already spiraling out of the control of the academies that teach these things.

It is only this generation, they say, that the youth and children are able to take the mad changes in stride, accepting it all as a part of day to day life.  Of those children, a small group of strange youths from the Lambsbridge Orphanage stand out, taking a more direct hand in events.`,

  arcs: [
    {
      label: "Arc 1",
      title: "Taking Root",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-1-taking-root/1-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Cynthia"},
      ],
    },
    {
      label: "Arc 2",
      title: "Cat out of the Bag",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-2-cat-out-of-the-bag/2-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Mauer"},
      ],
    },
    {
      label: "Arc 3",
      title: "Lips Sealed",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-3-lips-sealed/3-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Fray"},
      ],
    },
    {
      label: "Arc 4",
      title: "Stitch in Time",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-4-stitch-in-time/4-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Cynthia"},
      ],
    },
    {
      label: "Arc 5",
      title: "Esprit de Corpse",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-5-esprit-de-corpse/5-x/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Sanguine"},
      ],
    },
    {
      label: "Arc 6",
      title: "Lamb to the Slaughter",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-02-arc-6-lamb-to-the-slaughter/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-6-lamb-to-the-slaughter/6-x/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Avis"},
      ],
    },
    {
      label: "Arc 7",
      title: "Tooth and Nail",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-x-enemy/",  simplifiedTitle: "Interlude I", characterNamesTitle: "Interlude: Boys"},
        { url: "https://twigserial.wordpress.com/category/story/arc-7-tooth-and-nail/7-y-enemy-ii/",  simplifiedTitle: "Interlude II", characterNamesTitle: "Interlude: Girls"}
      ],
    },
      {
      label: "Arc 8",
      title: "Bleeding Edge",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-8-bleeding-edge/8-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Archduke"},
      ],
    },
    {
      label: "Arc 9",
      title: "Counting Sheep",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-17/", simplifiedTitle: "17"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-18/", simplifiedTitle: "18"},
        { url: "https://twigserial.wordpress.com/category/story/arc-9-counting-sheep/9-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
        {
      label: "Arc 10",
      title: "In Sheep's Clothing",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-17/", simplifiedTitle: "17"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-18/", simplifiedTitle: "18"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-19/", simplifiedTitle: "19"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-20/", simplifiedTitle: "20"},
        { url: "https://twigserial.wordpress.com/category/story/arc-10-in-sheeps-clothing/10-x-lamb/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
            {
      label: "Arc 11",
      title: "Cut to the Quick",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-03-arc-11-cut-to-the-quick/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-05-arc-11-cut-to-the-quick/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/2016/06/28/cut-to-the-quick-11-13/", simplifiedTitle: "13"}, // Category 11.13 has both 13 and 14. Directly linking to both, and hoping that it won't cause headaches updating the parser to unpack the two different types of chapter
        { url: "https://twigserial.wordpress.com/2016/06/30/cut-to-the-quick-11-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-11-cut-to-the-quick/11-x-lamb/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
      {
      label: "Arc 12",
      title: "Dyed in the Wool",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-12-dyed-in-the-wool/12-12/", simplifiedTitle: "12"},
      ],
    },
      {
      label: "Arc 13",
      title: "Black Sheep",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-01-arc-13-black-sheep/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-13-black-sheep/13-11/", simplifiedTitle: "11"},
      ],
    },
      {
      label: "Arc 14",
      title: "Thicker than Water",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-17/", simplifiedTitle: "17"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/14-18/", simplifiedTitle: "18"},
        { url: "https://twigserial.wordpress.com/category/story/arc-14-thicker-than-water/lamb-arc-14/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
            {
      label: "Arc 15",
      title: "Bitter Pill",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/15-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-15-bitter-pill/lamb-arc-15/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
        {
      label: "Arc 16",
      title: "Head over Heels",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-16-head-over-heels/16-x-lamb/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
      {
      label: "Arc 17",
      title: "Gut Feeling",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-17/", simplifiedTitle: "17"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-18/", simplifiedTitle: "18"},
        { url: "https://twigserial.wordpress.com/category/story/arc-17-gut-feeling/17-x-lambs/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: Lambs"},
      ],
    },
    {
      label: "Arc 18",
      title: "Dog Eat Dog",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-a-enemy/",  simplifiedTitle: "Interlude A", characterNamesTitle: "Interlude A: Enemy"}, // TODO
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-b-lamb/",   simplifiedTitle: "Interlude B", characterNamesTitle: "Interlude B: Lamb"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-c-enemy/", simplifiedTitle: "Interlude C", characterNamesTitle: "Interlude C: Enemy"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-d-lamb/",  simplifiedTitle: "Interlude D", characterNamesTitle: "Interlude D: Lamb"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-e-lamb/",  simplifiedTitle: "Interlude E", characterNamesTitle: "Interlude E: Lamb"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-f-enemy/", simplifiedTitle: "Interlude F", characterNamesTitle: "Interlude F: Enemy"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-g-enemy/", simplifiedTitle: "Interlude G", characterNamesTitle: "Interlude G: Enemy"},
        { url: "https://twigserial.wordpress.com/category/story/arc-18-dog-eat-dog-story/18-h-enemy/", simplifiedTitle: "Interlude H", characterNamesTitle: "Interlude H: Enemy"},
  ]
  },
            {
      label: "Arc 19",
      title: "Root and Branch",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-19-root-and-branch/19-x-enemy/",  simplifiedTitle: "Interlude", characterNamesTitle: "Interlude: ?"},
      ],
    },
          {
      label: "Arc 20",
      title: "Crown of Thorns",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-04/", simplifiedTitle: "4"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-05/", simplifiedTitle: "5"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-06/", simplifiedTitle: "6"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-07/", simplifiedTitle: "7"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-08/", simplifiedTitle: "8"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-09/", simplifiedTitle: "9"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-10/", simplifiedTitle: "10"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-11/", simplifiedTitle: "11"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-12/", simplifiedTitle: "12"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-13/", simplifiedTitle: "13"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-14/", simplifiedTitle: "14"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-15/", simplifiedTitle: "15"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-16/", simplifiedTitle: "16"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-17/", simplifiedTitle: "17"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-18/", simplifiedTitle: "18"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-19/", simplifiedTitle: "19"},
        { url: "https://twigserial.wordpress.com/category/story/arc-20-crown-of-thorns/20-20/", simplifiedTitle: "20"},
      ],
    },
    {
      label: "Epilogue",
      title: "Forest Through the Trees",
      chapters: [
        { url: "https://twigserial.wordpress.com/category/story/epilogue-arc-forest-for-the-trees/e-01/", simplifiedTitle: "1"},
        { url: "https://twigserial.wordpress.com/category/story/epilogue-arc-forest-for-the-trees/e-02/", simplifiedTitle: "2"},
        { url: "https://twigserial.wordpress.com/category/story/epilogue-arc-forest-for-the-trees/e-03/", simplifiedTitle: "3"},
        { url: "https://twigserial.wordpress.com/category/story/epilogue-arc-forest-for-the-trees/e-04/", simplifiedTitle: "4"}
      ]
    }
  ],
};
